### ISSUE TITLE
Raffle timing

### ISSUE THREAD

**Issue by Lullaboo** [chillroom/jacr-bot#12]
The raffle timer is off. sometimes really long intervals between beginning and being decided.

**Comment by qaisjp** [comment]
There's three messages in raffles: the initial announcement, the 20 second warning, and the final winner being decided. The delay between the initial announcement and the 20 second warning is 2 minutes.

Things will "stop working" if database data retrieval fails since this was how the original bot was built (**everything** polls the database).

If the current raffle system is too buggy, I'll add make it a priority feature on the new system.

Regardless, development will be slow this month and next month because of exams; and little or no work will be done until next Wednesday.

**Comment by qaisjp** [comment]
Fixed!
